# https://docs.digitalocean.com/glossary/app-spec
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/
# The app spec, is a YAML manifest that declaratively states everything about your app.
# Including each resource and all of your app’s environment variables and configuration variables.
name: 'bus-tracker-live'

# The domain names where the app is accessible on the public internet.
domains:
  - domain: 'bustracker.live'
    type: 'PRIMARY'

# The region to deploy the app into.
# See also: https://docs.digitalocean.com/products/platform/availability-matrix/#app-platform-availability
region: sfo

# Get alerts when things go horribly wrong.
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

services:
  # This is the backend for the push notifications demo,
  # the thing actually sending the push notifications.
  - name: 'api'
    github:
      branch: 'main'
      deploy_on_push: true
      repo: 'tix-factory/bus-tracker-live'
    health_check:
      http_path: '/application-metadata'
    http_port: 80
    instance_count: 1
    instance_size_slug: 'basic-xxs'
    routes:
      - path: /api
        preserve_path_prefix: true
    cors:
      allow_methods:
        - GET
      allow_origins:
        - exact: http://localhost:3000
        - exact: https://localhost:3000
    source_dir: 'services/api'
    dockerfile_path: 'services/api/Dockerfile'

static_sites:
  # This is the app that the humans interact with in their web browsers.
  - name: 'app'
    github:
      branch: 'main'
      deploy_on_push: true
      repo: 'tix-factory/bus-tracker-live'
    source_dir: 'services/app'
    output_dir: '/app/build'
    dockerfile_path: 'services/app/Dockerfile'
    routes:
      - path: /
    catchall_document: index.html
